### ISSUE TITLE
Why A Plugin?

### ISSUE THREAD

**Issue by bobrocke** [getgrav/grav-plugin-bootstrapper#2]
I don't have any reason not to like a plugin that is a dependency of a theme, such as Bootstrapper is to Bootstrap, but why is it needed?

What can, or is, done with the Bootstrapper plugin that could not be done with the Bootstrap theme and theme inheritance?

**Comment by rhukster** [comment]
A plugin can act like a 'behavior' in joomla.  i.e. another 3rd party plugin that displays a gallery for example, could have a dependency on the plugin to provide standard bootstrap CSS classes that it uses.   Otherwise you would have to say "to use this plugin you must have a theme that loads bootstrap" - pretty lame!

Another reason why you would want to use a plugin like this is to allow any theme to be easily upgraded with the latest bootstrap fixes.

**Comment by bobrocke** [comment]
Yes, other plugins could use it! That's the part I didn't consider.

I figured updating for new fixes wouldn't be a problem if an update was made to the theme and another theme had inherited from it.

**Comment by rhukster** [comment]
Still would be a problem if someone was using the orignal theme and had modified it slightly. Plugin removes at least the bootstrap css/js from that equation.
